### ISSUE TITLE
Menus not loading

### ISSUE THREAD

**Issue by BrandonHowe** [lunarcast/lunarbox#30]
Sometimes, after erroring out (and then requiring a refresh) the menus just never load. Even if I wait over a minute, or try to switch menus, they never appear.

**Comment by prescientmoon** [comment]
So they don't appear even after the refresh? Can you show me a screenshot?

**Comment by BrandonHowe** [comment]
![image](https://user-images.githubusercontent.com/35458851/80895770-9467f980-8cb6-11ea-8d9a-0efee566ea49.png)

I mean, there's really not much to see. The menus aren't open and therefore I cannot actually do anything.

**Comment by prescientmoon** [comment]
U have to press ctrl b or click the icon to open them

**Comment by BrandonHowe** [comment]
I clicked them, but it didn’t work.

**Comment by prescientmoon** [comment]
Did you click the same one being highlighted? When you click one which is not highlighted the focus is switched to that one. When you click the highlighted one the panel toggles

**Comment by prescientmoon** [comment]
Also did ctrl+b work?

**Comment by prescientmoon** [comment]
Since you seemed to have used this the wrong way I'll close it for now
