### ISSUE TITLE
"Cannot find inferred type"

### ISSUE THREAD

**Issue by BrandonHowe** [lunarcast/lunarbox#38]
**Describe the bug**
When making a function that has a dynamic output type, using that in main and then changing the function output type can produce the error.

**To Reproduce**
First, make a `Placeholder` function with an input node, an identity node, and an output node. Link all three up. The function should be a -> a.
Second, make the main function. Put a Placeholder node down and then give it an input with a defined type. In my screenshots, I use a String, but this applies to any type. Next, take a node whose input requires a type of the type you defined (in my case, string). Link up the placeholder to the node. In my pictures, I used a Length node.
Third, go back to the Placeholder function. Link up a node of a different type than the one you used in `main` (in my case, anything but a string) to the identity function. You can also just add a second input, and it will instantly crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/35458851/81444354-f99f6d00-9144-11ea-9390-37a5df0ffe46.png)
![image](https://user-images.githubusercontent.com/35458851/81444506-408d6280-9145-11ea-86cd-4f7f95d37362.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
fix please

**Comment by prescientmoon** [comment]
Update: pretty much fixed it on the #canvas branch. I still have to rewrite a bunch of stuff but soon it'll be done:)

**Comment by BrandonHowe** [comment]
Cool! This will be really great for UX, no more walking on eggshells when making complex functions.

**Comment by prescientmoon** [comment]
already fixed this, will be shipped in the next release
