### ISSUE TITLE
Bug in the Let generalization

### ISSUE THREAD

**Issue by prescientmoon** [lunarcast/lunarbox#42]
**Describe the bug**
Let expressions are over-generalized sometimes

**To Reproduce**
Add the following configuration:
![let](https://cdn.discordapp.com/attachments/672889285438865453/714094839087628358/bruh.png)

**Expected behavior**
The input should have a type of "Number"

**Desktop (please complete the following information):**
 - OS: Nixos
 - Browser Chrome
 - Version 1.16.2

**Additional context**
The compiled expression is:
```haskell
let id x = x in \x -> let y = id x in y + _
```

**Comment by MarinMario** [comment]
nice
